#!/usr/bin/env bash

##
#  U.SH/version
# -------------- -
#  author: Satoshi Soma (https://amekusa.com)
# ============================================ *
#
#  MIT License
#
#  Copyright (c) 2022 Satoshi Soma
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
##

base="$(dirname "$(dirname "$(realpath "$0")")")"
ver="$1"; shift
if [[ ! "$ver" =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
	cat <<- EOF >&2
	# USH/version
	Rewrites version numbers

	## Usage:
	version <N.N.N>

	EOF
	exit 1
fi

files=(
	"$base/load"
	"$base/README.md"
)
sedx="s|ver=\"[0-9]+\.[0-9]+\.[0-9]+\"|ver=\"$ver\"|g"
sedx="$sedx;s|v[0-9]+\.[0-9]+\.[0-9]+|v$ver|g"
for each in "${files[@]}"; do
	data="$(sed -E "$sedx" "$each")" && echo "$data" > "$each"
done

npm version "$ver"
