#!/usr/bin/env bash

# === FEED.SH ===
# by Satoshi Soma (github.com/amekusa)

_version="1.0.0"

_pid=$$
_interrupted=false
_status=""
_error=""
_done=0
_workers=0

_help() {
	cat << EOF
=== FEED.SH v$_version ===
By Satoshi Soma (github.com/amekusa)

Usage:
  feed -f <file> -c <command>

Example:
  feed -f urls.txt -c wget {item}
  feed -f urls.txt -c 'wget {item}'

Options:
  -h, --help     : Show this help.
  -f, --file     : Specify the file(s) to iterate over.
                   Each line in the file is treated as an "item",
                   and is passed to the command specified with '--cmd' option.
                   Lines that are empty or start with '#' are ignored.
  -c, --cmd      : Specify the command to run for each item.
                   Upon running, every occurrence of '{item}' in the command
                   gets replaced with the current item.
  -r, --replace  : Specify the placeholder string to be replaced in
                   the command. (default: {item})
  -w, --write    : Specify the file to save failed items.
                   The file can be passed to '--file' afterwards,
                   if you want to retry the failed items.
  -u, --update   : Save failed items to the same file as '--file'.
                   This option is a shortcut for like '-f items.txt -w items.txt'.
                   If '-f' was multiple, only the 1st file gets overwritten.
  -i, --interval : Set interval for eash iteration.
                   Examples: 5s, 10m, 1h
  -p, --parallel : Max number of processes to run in parallel. (default: 0)

EOF
}

_die() {
	echo "[ERROR] $1"
	exit 1
}

_main() {
	if [ -z "$1" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
		_help; return 1
	fi

	local file=() # files to read
	local cmd="" # command to run
	local replace="{item}" # placeholder to be replaced with each item
	local write="" # file to write
	local update=false # whether to overwrite '--file'
	local interval="" # iteration interval
	local parallel=0 # max processes to run in parallel

	# parsing args
	local ctx
	local err=false
	while [ $# -gt 0 ]; do
		case "$ctx" in
		cmd) # cmd context
			cmd="$cmd $1"
			;;
		*)
			case "$1" in
			-f|--file)
				ctx=file
				;;
			-c|--cmd)
				ctx=cmd
				;;
			-r|--replace)
				ctx=replace
				;;
			-w|--write)
				ctx=write
				;;
			-i|--interval)
				ctx=interval
				;;
			-p|--parallel)
				ctx=parallel
				;;
			-u|--update)
				update=true
				;;
			-*)
				err=true
				;;
			*)
				case "$ctx" in
				# contextual args
				file)
					file+=("$1")
					;;
				replace)
					replace="$1"
					ctx=
					;;
				write)
					write="$1"
					ctx=
					;;
				interval)
					interval="$1"
					ctx=
					;;
				parallel)
					parallel="$1"
					ctx=
					;;
				*)
					err=true
					;;
				esac
				;;
			esac
			;;
		esac
		$err && _die "invalid argument: '$1'"
		shift
	done
	[ -z "$cmd" ] && _die "specify command to run"
	cmd="${cmd:1}"

	# prepare a tmp file for logging
	local tmp
	if [ -n "$write" ] || "$update"; then
		if "$update"; then
			[ -n "$write" ] && _die "'--write' and '--update' are mutually exclusive"
			write="${file[0]}"
		fi
		tmp="$(mktemp)" || _die "failed to create a temp file"
		cat <<- EOF > "$tmp"
		# Failed Items @ $(date +'%F %H:%M:%S')
		# command: $cmd

		EOF
	fi

	# main loop
	local total=0
	local f; for f in "${file[@]}"; do
		local sleep
		local IFS line
		while IFS= read -r line; do
			# skip blank lines and comment lines
			if [ -z "$line" ] || [[ "$line" =~ ^[[:space:]]*# ]]; then
				continue
			fi

			((total++))

			# replace '{item}' in $cmd with $line
			local _cmd="${cmd//"$replace"/"$line"}"

			# handle ctrl+c
			if "$_interrupted"; then
				local now="$(date +'%F %H:%M:%S')"
				echo "$now [CANCEL] $_cmd"
				if [ -n "$tmp" ]; then
					cat <<- EOF >> "$tmp"
					# $now, interrupted by user
					$line

					EOF
				fi
				continue
			fi

			# sleep for interval
			[ -n "$sleep" ] && sleep "$sleep"

			# run the command
			((_workers++))
			if [ "$_workers" -le "$parallel" ]; then
				_run "$_cmd" "$line" "$tmp" &
			else
				_run "$_cmd" "$line" "$tmp"
			fi

			# set interval
			sleep="$interval"
		done < "$f"
	done

	wait

	local fails="$((total-_done))"
	cat <<- EOF

	--- FINISHED ---
	 Total items: $total
	Failed items: $fails

	EOF

	# flush the tmp file
	if [ -n "$tmp" ]; then
		cp -f "$tmp" "$write" &&
		rm "$tmp"
	fi

	if [ "$fails" -gt 0 ] && [ -z "$_status" ]; then
		_error="$fails items failed"
		_status=1
	fi

	if [ -n "$_status" ]; then
		echo "[ERROR] $_error"
		return "$_status"
	fi
}

_run() {
	local out
	if out="$(eval "$1" 2>&1)"; then
		# success
		echo "$(date +'%F %H:%M:%S') [DONE] $1"
		kill -s USR1 $_pid # send USR1 signal to self (or parent)
	else
		# failure
		local code="$?"
		local now="$(date +'%F %H:%M:%S')"
		echo "$now [FAIL] $1 (code:$code, err:$out)"
		if [ -n "$3" ]; then
			cat <<- EOF >> "$3"
			# $now, code:$code, err:$out
			$2

			EOF
		fi
		kill -s USR2 $_pid # send USR2 signal to self (or parent)
	fi
}

# signal handler: INT
_on_SIGINT() {
	echo
	echo "Terminating..."
	_interrupted=true
	_error="interrupted by user"
	_status=2
	wait
}

# signal handler: USR1
_on_SIGUSR1() {
	((_done++))
	((_workers--))
	wait
}

# signal handler: USR2
_on_SIGUSR2() {
	((_workers--))
	wait
}

# set signal handlers
trap _on_SIGINT INT
trap _on_SIGUSR1 USR1
trap _on_SIGUSR2 USR2

_main "$@"

